[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20160603003512-3d86f6c/master-haskell-20160603003512-3d86f6c"
  version = 1
  sha1 = "4fd979c87b2dfd7d8909ae052f3aeb66939b4bc2"

[build.dist-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  PUBLISH = "true"
  PUBLISH_EXECUTABLES = "tsrp"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"

[build.branches-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  PUBLISH = "true"
  PUBLISH_EXECUTABLES = "tsrp"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
